# Generated by Django 3.1.3 on 2020-12-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0002_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_action', models.CharField(choices=[('I', 'Identified'), ('W', 'watch'), ('F', 'fixed'), ('F', 'investigating')], max_length=1)),
                ('status_webstie', models.CharField(choices=[('D', 'Down'), ('U', 'up')], max_length=1)),
                ('website_name', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=30)),
                ('message', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
