# Generated by Django 3.1.3 on 2020-12-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0003_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
