# Generated by Django 3.1.3 on 2020-12-31 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0004_auto_20201226_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='website',
            new_name='incident',
        ),
    ]
