# Generated by Django 3.1.3 on 2020-12-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0005_auto_20201231_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='stickied',
            field=models.CharField(choices=[('Stikced', 'Stikced'), ('Un Stikced', 'Un Stikced')], default='Stikced', max_length=40),
        ),
    ]
