# Generated by Django 3.1.3 on 2020-12-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0006_incident_stickied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status_action',
            field=models.CharField(choices=[('Identified', 'identified'), ('Watch', 'watch'), ('Fixed', 'fixed'), ('Investigating', 'investigating')], max_length=40),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status_webstie',
            field=models.CharField(choices=[('Down', 'Down'), ('Uo', 'up')], max_length=40),
        ),
    ]
