# Generated by Django 3.1.3 on 2021-01-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0008_auto_20210101_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='status_webstie',
            new_name='status_website',
        ),
    ]
