# Generated by Django 3.1.3 on 2021-01-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0009_auto_20210110_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='message',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
