# Generated by Django 3.1.3 on 2021-01-11 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0010_auto_20210111_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date_occur',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
