# Generated by Django 3.1.3 on 2021-01-12 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0011_incident_date_occur'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_maintance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=40)),
                ('when', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
