# Generated by Django 3.1.4 on 2021-01-12 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0012_schedule_maintance'),
    ]

    operations = [
        migrations.CreateModel(
            name='component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('Description', models.TextField(blank=True, max_length=300)),
                ('when', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('link', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='component_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('Description', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='website_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='status_website',
            new_name='status_Downtime',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='url',
        ),
        migrations.AddField(
            model_name='incident',
            name='Visibility',
            field=models.CharField(choices=[('Viewable by public', 'Viewable by public'), ('Only logged in users can see', 'Only logged in users can see')], default='Viewable by public', max_length=40),
        ),
    ]
