# Generated by Django 3.1.3 on 2021-01-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0013_auto_20210113_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status_Downtime',
            field=models.CharField(choices=[('Down', 'Down'), ('Up', 'up')], default='Up', max_length=40),
        ),
        migrations.AlterField(
            model_name='schedule_maintance',
            name='message',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
