# Generated by Django 3.1.3 on 2021-01-14 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0014_auto_20210113_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='historical_del_incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='group',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='silinell.component_group'),
        ),
    ]
