# Generated by Django 3.1.3 on 2021-01-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0015_auto_20210114_0749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historical_del_incident',
        ),
    ]
