# Generated by Django 3.1.3 on 2021-01-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0016_delete_historical_del_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='historical_del_incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
