# Generated by Django 3.1.3 on 2021-01-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0017_historical_del_incident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historical_del_incident',
        ),
    ]
