# Generated by Django 3.1.3 on 2021-01-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0019_auto_20210114_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='group',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
