# Generated by Django 3.1.3 on 2021-01-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0022_auto_20210114_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='group',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
