# Generated by Django 3.1.3 on 2021-01-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silinell', '0024_auto_20210114_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_group',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
